version: '3.4'

services:
  virtocommerce.storefront:
    environment:
      - VirtoCommerce__Endpoint__Url=${PLATFORM_URL}
      - VirtoCommerce__Endpoint__UserName=admin
      - VirtoCommerce__Endpoint__Password=store
      - ASPNETCORE_ENVIRONMENT=Development 
    ports:
      - "${DOCKER_STOREFRONT_PORT:-8080}:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${CMS_CONTENT_VOLUME}:/app/wwwroot/cms-content
    networks:
        - virto

networks:
  virto:
    external:
      name: nat        
